<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Mensuration Match — master catalog
    |--------------------------------------------------------------------------
    | boards: perimeter_area | volume
    | classes: "all" or list of class numbers (sort_order), e.g. [5,6,7,8,9,10]
    */
    'items' => [
        [
            'key' => 'perim_circle',
            'board' => 'perimeter_area',
            'measure' => 'perimeter',
            'figure' => 'circle',
            'title' => 'Circle',
            'story' => 'I start walking from point A around a circle of radius r and come back. I cover ____.',
            'formula' => '2πr',
            'classes' => 'all',
            'diagram' => 'circle_walk',
        ],
        [
            'key' => 'perim_rectangle',
            'board' => 'perimeter_area',
            'measure' => 'perimeter',
            'figure' => 'rectangle',
            'title' => 'Rectangle',
            'story' => 'I start at A and walk around a rectangle of length l and breadth b back to A. I cover ____.',
            'formula' => '2(l+b)',
            'classes' => 'all',
            'diagram' => 'rectangle_walk',
        ],
        [
            'key' => 'perim_triangle',
            'board' => 'perimeter_area',
            'measure' => 'perimeter',
            'figure' => 'triangle',
            'title' => 'Triangle',
            'story' => 'I walk along all three sides a, b and c of a triangle and return. I cover ____.',
            'formula' => 'a+b+c',
            'classes' => 'all',
            'diagram' => 'triangle_walk',
        ],
        [
            'key' => 'perim_parallelogram',
            'board' => 'perimeter_area',
            'measure' => 'perimeter',
            'figure' => 'parallelogram',
            'title' => 'Parallelogram',
            'story' => 'I walk around a parallelogram with adjacent sides a and b. I cover ____.',
            'formula' => '2(a+b)',
            'classes' => [5, 6, 7, 8, 9, 10],
            'diagram' => 'parallelogram_walk',
        ],
        [
            'key' => 'area_circle',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'circle',
            'title' => 'Circle area',
            'story' => 'I paint the whole disc of radius r. The area I cover is ____.',
            'formula' => 'πr²',
            'classes' => [5, 6, 7, 8, 9, 10],
            'diagram' => 'circle_area',
        ],
        [
            'key' => 'area_rectangle',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'rectangle',
            'title' => 'Rectangle area',
            'story' => 'I tile a rectangular floor of length l and breadth b. The area is ____.',
            'formula' => 'l×b',
            'classes' => [5, 6, 7, 8, 9, 10],
            'diagram' => 'rectangle_area',
        ],
        [
            'key' => 'area_triangle',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'triangle',
            'title' => 'Triangle area',
            'story' => 'I cover a triangle with base b and height h. The area is ____.',
            'formula' => '½bh',
            'classes' => [5, 6, 7, 8, 9, 10],
            'diagram' => 'triangle_area',
        ],
        [
            'key' => 'area_parallelogram',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'parallelogram',
            'title' => 'Parallelogram area',
            'story' => 'I cover a parallelogram with base b and height h. The area is ____.',
            'formula' => 'b×h',
            'classes' => [5, 6, 7, 8, 9, 10],
            'diagram' => 'parallelogram_area',
        ],
        [
            'key' => 'area_sphere',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'sphere',
            'title' => 'Sphere surface',
            'story' => 'I wrap the whole outer surface of a sphere of radius r. The surface area is ____.',
            'formula' => '4πr²',
            'classes' => [5, 6, 7, 8, 9, 10],
            'diagram' => 'sphere_surface',
        ],
        [
            'key' => 'area_cylinder_lateral',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'cylinder',
            'title' => 'Cylinder lateral surface',
            'story' => 'I wrap only the curved side of a cylinder of radius r and height h (not the top or bottom). The lateral surface area is ____.',
            'formula' => '2πrh',
            'classes' => [8, 9, 10],
            'diagram' => 'cylinder_lateral',
        ],
        [
            'key' => 'area_cylinder_total',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'cylinder',
            'title' => 'Cylinder total surface',
            'story' => 'I wrap the curved side and both flat ends of a cylinder of radius r and height h. The total surface area is ____.',
            'formula' => '2πr(h+r)',
            'classes' => [8, 9, 10],
            'diagram' => 'cylinder_total',
        ],
        [
            'key' => 'area_cone_lateral',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'cone',
            'title' => 'Cone lateral surface',
            'story' => 'I wrap only the curved surface of a cone of radius r and slant height l (not the circular base). The lateral surface area is ____.',
            'formula' => 'πrl',
            'classes' => [8, 9, 10],
            'diagram' => 'cone_lateral',
        ],
        [
            'key' => 'area_cone_total',
            'board' => 'perimeter_area',
            'measure' => 'area',
            'figure' => 'cone',
            'title' => 'Cone total surface',
            'story' => 'I wrap the curved surface and the circular base of a cone of radius r and slant height l. The total surface area is ____.',
            'formula' => 'πr(l+r)',
            'classes' => [8, 9, 10],
            'diagram' => 'cone_total',
        ],
        [
            'key' => 'vol_cylinder',
            'board' => 'volume',
            'measure' => 'volume',
            'figure' => 'cylinder',
            'title' => 'Cylinder',
            'story' => 'I fill a cylinder glass of radius r and height h with water. The volume is ____.',
            'formula' => 'πr²h',
            'classes' => [8, 9, 10],
            'diagram' => 'cylinder_fill',
        ],
        [
            'key' => 'vol_cube',
            'board' => 'volume',
            'measure' => 'volume',
            'figure' => 'cube',
            'title' => 'Cube',
            'story' => 'I fill a cube of edge a. The volume is ____.',
            'formula' => 'a³',
            'classes' => [8, 9, 10],
            'diagram' => 'cube_fill',
        ],
        [
            'key' => 'vol_cuboid',
            'board' => 'volume',
            'measure' => 'volume',
            'figure' => 'cuboid',
            'title' => 'Cuboid',
            'story' => 'I fill a cuboid of length l, breadth b and height h. The volume is ____.',
            'formula' => 'l×b×h',
            'classes' => [8, 9, 10],
            'diagram' => 'cuboid_fill',
        ],
        [
            'key' => 'vol_sphere',
            'board' => 'volume',
            'measure' => 'volume',
            'figure' => 'sphere',
            'title' => 'Sphere',
            'story' => 'I fill a spherical ball of radius r. The volume is ____.',
            'formula' => '4/3πr³',
            'classes' => [8, 9, 10],
            'diagram' => 'sphere_fill',
        ],
    ],
];
